### ISSUE TITLE
Issue in jbovlaste English pdf export

### ISSUE THREAD

**Issue by lancioni** [lojban/jbovlaste#202] opened 2018-03-07 14:30 UTC
There is a problem in the pdf Printable Dictionary for English: the output ends at page 442 (last entry pevyca’o zei uidje). The .tex file seems to be complete; unfortunately, MikTeX gives me errors and I cannot produce the pdf file myself. I guess there is some offending instruction in the .text file.

Greetings,

Giuliano

**Comment by lagleki** [comment] 2018-03-07 14:41
duplicate of https://github.com/lojban/jbovlaste/issues/180

**Closed by lagleki** 2018-03-07 14:41 UTC
