### ISSUE TITLE
PDF export is incomplete in English

### ISSUE THREAD

**Issue by tady159** [lojban/jbovlaste#198] opened 2016-07-26 18:42 UTC
I have requested a PDF export in English, and the resulting file seems to be incomplete. It has 286 pages, but ends on the entry "iartsagunbu", and I suppose it should go up to the letter Z.
Generating the dictionary in Lojban results in 94 pages and seems to be complete (ends with entry "zy")

**Comment by lagleki** [comment] 2016-07-27 08:23
duplicate of https://github.com/lojban/jbovlaste/issues/180

fixed for you. must work now.

**Closed by lagleki** 2016-07-27 08:23 UTC
